### ISSUE TITLE
`getApiV1AddressesP1Transactions` also return fee box when concise=true

### ISSUE THREAD

**Issue by capt-nemo429** [ergoplatform/explorer-backend#194]
Useful information for in-wallet displaying.

**Comment by MrStahlfelge** [comment]
Not sure about this. When a tx is sent, the fee is included in the inboxes from the address. When received, tx is not really interesting.

**Comment by MrStahlfelge** [comment]
> @MrStahlfelge will this feature make use of concise mode less convenient for you?

No, it is okay for me - I have a filter on the output in any case.

**Comment by capt-nemo429** [comment]
> @capt-nemo429 do you need it to determine tx fee in Nautilus?

Yeah, also for csv history exporting

**Comment by capt-nemo429** [comment]
As @monyedavid is already on #202, which is better for Nautilus, so this issue can be closed if @MrStahlfelge agrees.

**Comment by MrStahlfelge** [comment]
Yes I don't need fee box. Can be closed 👍
