### ISSUE TITLE
Support Height for getting Tx

### ISSUE THREAD

**Issue by vorujack** [ergoplatform/explorer-backend#202]
When requesting transactions of an address, in addition to pagination, the inclusion height of transactions can be searched

for example

```
/api/v1/addresses/<selected-address>/transactions?fromHeight=3999&toHeight=4999&limit=10&offset=10
```

**Comment by capt-nemo429** [comment]
I agree, this is specially useful for transaction history syncing

**Comment by capt-nemo429** [comment]
@monyedavid thank you )

**Comment by monyedavid** [comment]
#207
