### ISSUE TITLE
parameter concise in  /api/v1/addresses/{p1}/transactions does not work.

### ISSUE THREAD

**Issue by vorujack** [ergoplatform/explorer-backend#203]
when we calling transactions of one address get a complete list of transactions with complete inputs and outputs.

but calling it with concise=true cause to return an empty list of output.

```
https://api.ergoplatform.com/api/v1/addresses/9hN2UY1ZvvWMeWRBso28vSyjrAAfGJHh2DkZpE47J7Wqr51YLAR/transactions?concise=true
```
returns 

```
{"items":[],"total":3}
```

**Comment by MrStahlfelge** [comment]
See #193
