### ISSUE TITLE
sortBy="transactionsCount" doesn't work

### ISSUE THREAD

**Issue by deadit** [ergoplatform/explorer-backend#37]
https://new-explorer.ergoplatform.com/blocks?limit=30&offset=0&sortBy=transactionsCount&sortDirection=asc

<img width="435" alt="Снимок экрана 2020-05-05 в 19 51 17" src="https://user-images.githubusercontent.com/26635501/81092936-06844c80-8f0a-11ea-9df8-dea54a15582c.png">

**Comment by oskin1** [comment]
Fixed
