### ISSUE TITLE
Detailed UTXO-Set Search Queries

### ISSUE THREAD

**Issue by robkorn** [ergoplatform/explorer-backend#74]
In the near future we will need the explorer-backend to support detailed search queries for finding UTXOs in the existing UTXO-set. This is to provide a very streamlined experience for end users of dApps to find the required UTXOs they need to perform actions/submit txs.

And example of queries we will need for a UTXO:
- At P2S address X
- Holds token with ID Y of amount A
- In R4 has P2S address Z
- In R5 has i32 26472
- In R6 has public key P

(and effectively have support for searching for all datatypes within registers)

**Comment by oskin1** [comment]
Depends on #86

**Comment by robkorn** [comment]
@oskin1 As a heads up, in the interim we could cover likely 75% of use cases by being able to search for boxes by address/Token IDs and then filtering the few boxes which we get as a response. The register reading is a great plus, but if it's a big undertaking then for the shorter-term just having address + token id could be a good intermediary goal.

**Comment by oskin1** [comment]
Implemented in #105
